/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 room.gltf 
Author: Phons (https://sketchfab.com/Phons)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cyberpunk-room-cubicle-0740c506707e4678a96dc6b705037574
Title: Cyberpunk Room Cubicle
*/

import React, { useEffect, useRef, useState } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber';

export default function Model(props) {
  const { nodes, materials } = useGLTF('/model/room.gltf');
  
  const groupRef = useRef();
  
  // Postavljanje stanja za smjer rotacije
  const rotationDirectionRef = useRef(1); // 1 za rotaciju u pozitivnom smjeru, -1 za rotaciju u negativnom smjeru

  // Funkcija za rotaciju i translaciju
  useFrame(() => {
    // Rotacija
    groupRef.current.rotation.x = 0.3
    groupRef.current.rotation.y += 0.01 * rotationDirectionRef.current;

    // Promjena smjera rotacije kada dostignemo određenu točku
    if (groupRef.current.rotation.y >= 0) {
      rotationDirectionRef.current = -1;
    } else if (groupRef.current.rotation.y <= -1.8) {
      rotationDirectionRef.current = 1;
    }
  });

  return (
    <group {...props} dispose={null} ref={groupRef} position={[0.198, -3.124, -15.827]}>
      <group>
        <mesh geometry={nodes.Object_4.geometry} material={materials.Material} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.Yeet} />
      </group>
    </group>
  )
}

useGLTF.preload('/model/room.gltf');
